version: '2'

services:
  email:
    restart: always
    build:
      context: ./smtpserver
      dockerfile: Dockerfile
    image: webservice_emails
    depends_on:
      - mysqldb
      - mongodb
    ports:
     - "25:25"
    volumes:
     - ./smtpserver:/emailapp
  web:
    restart: always
    build:
      context: ./web
      dockerfile: Dockerfile
    image: webservice_flask
    depends_on:
      - mysqldb
      - mongodb
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./web:/app
  front:
    restart: always
    image: webservice_angular4
    build: ./front
    ports:
     - "3000:3000"
     - "3001:3001"
     - "8080:8080"
    volumes:
     - ./front:/tmp/cache
  mysqldb:
    restart: always
    hostname: mysqlserver
    image: hypriot/rpi-mysql
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASS: test_password
    volumes:
      - mysqldata:/var/lib/mysql
  mongodb:
    restart: always
    hostname: mongoserver
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: rpi-mongo:3.4.5
    ports:
     - "27017:27017"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodata:/data/db
    command: mongod --smallfiles --logpath=/dev/nul
volumes:
  mysqldata:
  mongodata:
