version: '2'

services:
  email:
    restart: always
    build:
      context: ./smtpserver
      dockerfile: Dockerfilex86
    image: webservice_emails
    depends_on:
      - mysqldb
    ports:
     - "25:25"
  web:
    restart: always
    build:
      context: ./web
      dockerfile: Dockerfilex86
    image: webservice_flask
    depends_on:
      - mysqldb
    ports:
     - "80:80"
     - "443:443"
  front:
    restart: always
    image: webservice_angular4
    build:
      context: ./front
      dockerfile: Dockerfilex86
    ports:
     - "3000:3000"
     - "3001:3001"
     - "8080:8080"
    volumes:
     - ./front:/tmp/cache
  mysqldb:
    image: mysql:5.6.26
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASS: my-secret-pw
    ports:
      - "3306:3306"
    restart: always
    hostname: mysqldb
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
