version: '2'

services:
  email:
    restart: always
    build:
      context: ./smtpserver
      dockerfile: Dockerfile
    image: webservice_emails
    depends_on:
      - db
    ports:
     - "25:25"
    volumes:
     - ./smtpserver:/emailapp
  web:
    restart: always
    build:
      context: ./web
      dockerfile: Dockerfile
    image: webservice_flask
    depends_on:
      - db
    ports:
     - "80:80"
     - "443:80"
    volumes:
     - ./web:/app
  front:
    restart: always
    image: webservice_angular4
    build: ./front
    ports:
     - "3000:3000"
     - "3001:3001"
     - "8080:8080"
    volumes:
     - ./front:/tmp/cache
  db:
    restart: always
    hostname: mysqlserver
    image: hypriot/rpi-mysql
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASS: test_password
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
